CREATE TABLE [dbo].[Region]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
	[KazaId] UNIQUEIDENTIFIER NULL, 
    [NameAr] NVARCHAR(100) NOT NULL, 
    [NameFo] NVARCHAR(100) NOT NULL,
    CONSTRAINT [FK_Region_ToTable] FOREIGN KEY ([KazaId]) REFERENCES [Kaza]([Id])
)
